/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'productId' : bigint, 'quantity' : bigint }
export type Category = { 'clothing' : null } |
  { 'accessories' : null } |
  { 'footwear' : null };
export interface Deal {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'isActive' : boolean,
  'discount' : bigint,
  'products' : Array<Product>,
  'isFlashSale' : boolean,
}
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'trackingInfo' : [] | [string],
  'total' : bigint,
  'user' : Principal,
  'timestamp' : Time,
  'shippingAddress' : string,
  'items' : Array<CartItem>,
}
export type OrderStatus = { 'shipped' : null } |
  { 'delivered' : null } |
  { 'processing' : null };
export interface Product {
  'id' : bigint,
  'trendTags' : Array<string>,
  'name' : string,
  'videoPreview' : [] | [string],
  'description' : string,
  'category' : Category,
  'price' : bigint,
  'vibeTags' : Array<VibeTag>,
  'images' : Array<string>,
}
export interface Review {
  'id' : bigint,
  'text' : string,
  'user' : Principal,
  'productId' : bigint,
  'isInfluencerPick' : boolean,
  'rating' : bigint,
  'influencerQuote' : [] | [string],
}
export interface StylePreferences {
  'preferredCategories' : Array<Category>,
  'excludedColors' : [] | [Array<string>],
  'dislikedVibes' : Array<VibeTag>,
  'budgetRange' : [bigint, bigint],
  'preferredVibes' : Array<VibeTag>,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'shippingAddress' : string,
  'stylePreferences' : StylePreferences,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VibeTag = { 'Y2K' : null } |
  { 'minimal' : null } |
  { 'streetwear' : null } |
  { 'casual' : null } |
  { 'party' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'addReview' : ActorMethod<[Review], undefined>,
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateCartTotal' : ActorMethod<[], bigint>,
  'checkout' : ActorMethod<[], bigint>,
  'createDeal' : ActorMethod<[Deal], undefined>,
  'getActiveDeals' : ActorMethod<[], Array<Deal>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAverageRating' : ActorMethod<[bigint], number>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[Principal], Array<CartItem>>,
  'getFlashSales' : ActorMethod<[], Array<Deal>>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProductReviews' : ActorMethod<[bigint], Array<Review>>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'getProductsByVibe' : ActorMethod<[VibeTag], Array<Product>>,
  'getRecommendedOutfits' : ActorMethod<[], Array<Product>>,
  'getUserOrders' : ActorMethod<[Principal], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];