/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'clothing' : IDL.Null,
  'accessories' : IDL.Null,
  'footwear' : IDL.Null,
});
export const VibeTag = IDL.Variant({
  'Y2K' : IDL.Null,
  'minimal' : IDL.Null,
  'streetwear' : IDL.Null,
  'casual' : IDL.Null,
  'party' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'trendTags' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'videoPreview' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'category' : Category,
  'price' : IDL.Nat,
  'vibeTags' : IDL.Vec(VibeTag),
  'images' : IDL.Vec(IDL.Text),
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'user' : IDL.Principal,
  'productId' : IDL.Nat,
  'isInfluencerPick' : IDL.Bool,
  'rating' : IDL.Nat,
  'influencerQuote' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Deal = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'discount' : IDL.Nat,
  'products' : IDL.Vec(Product),
  'isFlashSale' : IDL.Bool,
});
export const StylePreferences = IDL.Record({
  'preferredCategories' : IDL.Vec(Category),
  'excludedColors' : IDL.Opt(IDL.Vec(IDL.Text)),
  'dislikedVibes' : IDL.Vec(VibeTag),
  'budgetRange' : IDL.Tuple(IDL.Nat, IDL.Nat),
  'preferredVibes' : IDL.Vec(VibeTag),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'shippingAddress' : IDL.Text,
  'stylePreferences' : StylePreferences,
});
export const CartItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'delivered' : IDL.Null,
  'processing' : IDL.Null,
});
export const Time = IDL.Int;
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'trackingInfo' : IDL.Opt(IDL.Text),
  'total' : IDL.Nat,
  'user' : IDL.Principal,
  'timestamp' : Time,
  'shippingAddress' : IDL.Text,
  'items' : IDL.Vec(CartItem),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func([Product], [], []),
  'addReview' : IDL.Func([Review], [], []),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateCartTotal' : IDL.Func([], [IDL.Nat], []),
  'checkout' : IDL.Func([], [IDL.Nat], []),
  'createDeal' : IDL.Func([Deal], [], []),
  'getActiveDeals' : IDL.Func([], [IDL.Vec(Deal)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAverageRating' : IDL.Func([IDL.Nat], [IDL.Float64], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([IDL.Principal], [IDL.Vec(CartItem)], ['query']),
  'getFlashSales' : IDL.Func([], [IDL.Vec(Deal)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProductReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'getProductsByVibe' : IDL.Func([VibeTag], [IDL.Vec(Product)], ['query']),
  'getRecommendedOutfits' : IDL.Func([], [IDL.Vec(Product)], []),
  'getUserOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFromCart' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'clothing' : IDL.Null,
    'accessories' : IDL.Null,
    'footwear' : IDL.Null,
  });
  const VibeTag = IDL.Variant({
    'Y2K' : IDL.Null,
    'minimal' : IDL.Null,
    'streetwear' : IDL.Null,
    'casual' : IDL.Null,
    'party' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'trendTags' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'videoPreview' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'category' : Category,
    'price' : IDL.Nat,
    'vibeTags' : IDL.Vec(VibeTag),
    'images' : IDL.Vec(IDL.Text),
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'user' : IDL.Principal,
    'productId' : IDL.Nat,
    'isInfluencerPick' : IDL.Bool,
    'rating' : IDL.Nat,
    'influencerQuote' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Deal = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'discount' : IDL.Nat,
    'products' : IDL.Vec(Product),
    'isFlashSale' : IDL.Bool,
  });
  const StylePreferences = IDL.Record({
    'preferredCategories' : IDL.Vec(Category),
    'excludedColors' : IDL.Opt(IDL.Vec(IDL.Text)),
    'dislikedVibes' : IDL.Vec(VibeTag),
    'budgetRange' : IDL.Tuple(IDL.Nat, IDL.Nat),
    'preferredVibes' : IDL.Vec(VibeTag),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'shippingAddress' : IDL.Text,
    'stylePreferences' : StylePreferences,
  });
  const CartItem = IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'delivered' : IDL.Null,
    'processing' : IDL.Null,
  });
  const Time = IDL.Int;
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'trackingInfo' : IDL.Opt(IDL.Text),
    'total' : IDL.Nat,
    'user' : IDL.Principal,
    'timestamp' : Time,
    'shippingAddress' : IDL.Text,
    'items' : IDL.Vec(CartItem),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func([Product], [], []),
    'addReview' : IDL.Func([Review], [], []),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateCartTotal' : IDL.Func([], [IDL.Nat], []),
    'checkout' : IDL.Func([], [IDL.Nat], []),
    'createDeal' : IDL.Func([Deal], [], []),
    'getActiveDeals' : IDL.Func([], [IDL.Vec(Deal)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAverageRating' : IDL.Func([IDL.Nat], [IDL.Float64], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([IDL.Principal], [IDL.Vec(CartItem)], ['query']),
    'getFlashSales' : IDL.Func([], [IDL.Vec(Deal)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProductReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsByVibe' : IDL.Func([VibeTag], [IDL.Vec(Product)], ['query']),
    'getRecommendedOutfits' : IDL.Func([], [IDL.Vec(Product)], []),
    'getUserOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFromCart' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };