/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Review {
    id: bigint;
    text: string;
    user: Principal;
    productId: bigint;
    isInfluencerPick: boolean;
    rating: bigint;
    influencerQuote?: string;
}
export type Time = bigint;
export interface Deal {
    id: bigint;
    title: string;
    description: string;
    isActive: boolean;
    discount: bigint;
    products: Array<Product>;
    isFlashSale: boolean;
}
export interface StylePreferences {
    preferredCategories: Array<Category>;
    excludedColors?: Array<string>;
    dislikedVibes: Array<VibeTag>;
    budgetRange: [bigint, bigint];
    preferredVibes: Array<VibeTag>;
}
export interface CartItem {
    productId: bigint;
    quantity: bigint;
}
export interface Order {
    id: bigint;
    status: OrderStatus;
    trackingInfo?: string;
    total: bigint;
    user: Principal;
    timestamp: Time;
    shippingAddress: string;
    items: Array<CartItem>;
}
export interface Product {
    id: bigint;
    trendTags: Array<string>;
    name: string;
    videoPreview?: string;
    description: string;
    category: Category;
    price: bigint;
    vibeTags: Array<VibeTag>;
    images: Array<string>;
}
export interface UserProfile {
    name: string;
    email: string;
    shippingAddress: string;
    stylePreferences: StylePreferences;
}
export enum Category {
    clothing = "clothing",
    accessories = "accessories",
    footwear = "footwear"
}
export enum OrderStatus {
    shipped = "shipped",
    delivered = "delivered",
    processing = "processing"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VibeTag {
    Y2K = "Y2K",
    minimal = "minimal",
    streetwear = "streetwear",
    casual = "casual",
    party = "party"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addProduct(product: Product): Promise<void>;
    addReview(review: Review): Promise<void>;
    addToCart(productId: bigint, quantity: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    calculateCartTotal(): Promise<bigint>;
    checkout(): Promise<bigint>;
    createDeal(deal: Deal): Promise<void>;
    getActiveDeals(): Promise<Array<Deal>>;
    getAllProducts(): Promise<Array<Product>>;
    getAverageRating(productId: bigint): Promise<number>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCart(callerId: Principal): Promise<Array<CartItem>>;
    getFlashSales(): Promise<Array<Deal>>;
    getOrder(orderId: bigint): Promise<Order | null>;
    getProduct(productId: bigint): Promise<Product | null>;
    getProductReviews(productId: bigint): Promise<Array<Review>>;
    getProductsByCategory(category: Category): Promise<Array<Product>>;
    getProductsByVibe(vibe: VibeTag): Promise<Array<Product>>;
    getRecommendedOutfits(): Promise<Array<Product>>;
    getUserOrders(userId: Principal): Promise<Array<Order>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    removeFromCart(productId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { CartItem as _CartItem, Category as _Category, Deal as _Deal, Order as _Order, OrderStatus as _OrderStatus, Product as _Product, Review as _Review, StylePreferences as _StylePreferences, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, VibeTag as _VibeTag } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(to_candid_Product_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(to_candid_Product_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addReview(arg0: Review): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addReview(to_candid_Review_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReview(to_candid_Review_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addToCart(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToCart(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToCart(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async calculateCartTotal(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateCartTotal();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateCartTotal();
            return result;
        }
    }
    async checkout(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.checkout();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkout();
            return result;
        }
    }
    async createDeal(arg0: Deal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createDeal(to_candid_Deal_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDeal(to_candid_Deal_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getActiveDeals(): Promise<Array<Deal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveDeals();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveDeals();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAverageRating(arg0: bigint): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getAverageRating(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAverageRating(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCart(arg0: Principal): Promise<Array<CartItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCart(arg0);
            return result;
        }
    }
    async getFlashSales(): Promise<Array<Deal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFlashSales();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFlashSales();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: bigint): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: bigint): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductReviews(arg0: bigint): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductReviews(arg0);
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductReviews(arg0);
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductsByCategory(arg0: Category): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByCategory(to_candid_Category_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByCategory(to_candid_Category_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductsByVibe(arg0: VibeTag): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByVibe(to_candid_VibeTag_n6(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByVibe(to_candid_VibeTag_n6(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecommendedOutfits(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecommendedOutfits();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecommendedOutfits();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserOrders(arg0: Principal): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserOrders(arg0);
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserOrders(arg0);
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeFromCart(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromCart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromCart(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n46(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n46(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Category_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Deal_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Deal): Deal {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Review_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Review): Review {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_StylePreferences_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StylePreferences): StylePreferences {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_VibeTag_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VibeTag): VibeTag {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<string>]): Array<string> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : from_candid_Product_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    description: string;
    isActive: boolean;
    discount: bigint;
    products: Array<_Product>;
    isFlashSale: boolean;
}): {
    id: bigint;
    title: string;
    description: string;
    isActive: boolean;
    discount: bigint;
    products: Array<Product>;
    isFlashSale: boolean;
} {
    return {
        id: value.id,
        title: value.title,
        description: value.description,
        isActive: value.isActive,
        discount: value.discount,
        products: from_candid_vec_n18(_uploadFile, _downloadFile, value.products),
        isFlashSale: value.isFlashSale
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    trendTags: Array<string>;
    name: string;
    videoPreview: [] | [string];
    description: string;
    category: _Category;
    price: bigint;
    vibeTags: Array<_VibeTag>;
    images: Array<string>;
}): {
    id: bigint;
    trendTags: Array<string>;
    name: string;
    videoPreview?: string;
    description: string;
    category: Category;
    price: bigint;
    vibeTags: Array<VibeTag>;
    images: Array<string>;
} {
    return {
        id: value.id,
        trendTags: value.trendTags,
        name: value.name,
        videoPreview: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.videoPreview)),
        description: value.description,
        category: from_candid_Category_n22(_uploadFile, _downloadFile, value.category),
        price: value.price,
        vibeTags: from_candid_vec_n24(_uploadFile, _downloadFile, value.vibeTags),
        images: value.images
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    shippingAddress: string;
    stylePreferences: _StylePreferences;
}): {
    name: string;
    email: string;
    shippingAddress: string;
    stylePreferences: StylePreferences;
} {
    return {
        name: value.name,
        email: value.email,
        shippingAddress: value.shippingAddress,
        stylePreferences: from_candid_StylePreferences_n30(_uploadFile, _downloadFile, value.stylePreferences)
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    preferredCategories: Array<_Category>;
    excludedColors: [] | [Array<string>];
    dislikedVibes: Array<_VibeTag>;
    budgetRange: [bigint, bigint];
    preferredVibes: Array<_VibeTag>;
}): {
    preferredCategories: Array<Category>;
    excludedColors?: Array<string>;
    dislikedVibes: Array<VibeTag>;
    budgetRange: [bigint, bigint];
    preferredVibes: Array<VibeTag>;
} {
    return {
        preferredCategories: from_candid_vec_n32(_uploadFile, _downloadFile, value.preferredCategories),
        excludedColors: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.excludedColors)),
        dislikedVibes: from_candid_vec_n24(_uploadFile, _downloadFile, value.dislikedVibes),
        budgetRange: value.budgetRange,
        preferredVibes: from_candid_vec_n24(_uploadFile, _downloadFile, value.preferredVibes)
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _OrderStatus;
    trackingInfo: [] | [string];
    total: bigint;
    user: Principal;
    timestamp: _Time;
    shippingAddress: string;
    items: Array<_CartItem>;
}): {
    id: bigint;
    status: OrderStatus;
    trackingInfo?: string;
    total: bigint;
    user: Principal;
    timestamp: Time;
    shippingAddress: string;
    items: Array<CartItem>;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n39(_uploadFile, _downloadFile, value.status),
        trackingInfo: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.trackingInfo)),
        total: value.total,
        user: value.user,
        timestamp: value.timestamp,
        shippingAddress: value.shippingAddress,
        items: value.items
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    text: string;
    user: Principal;
    productId: bigint;
    isInfluencerPick: boolean;
    rating: bigint;
    influencerQuote: [] | [string];
}): {
    id: bigint;
    text: string;
    user: Principal;
    productId: bigint;
    isInfluencerPick: boolean;
    rating: bigint;
    influencerQuote?: string;
} {
    return {
        id: value.id,
        text: value.text,
        user: value.user,
        productId: value.productId,
        isInfluencerPick: value.isInfluencerPick,
        rating: value.rating,
        influencerQuote: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.influencerQuote))
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    clothing: null;
} | {
    accessories: null;
} | {
    footwear: null;
}): Category {
    return "clothing" in value ? Category.clothing : "accessories" in value ? Category.accessories : "footwear" in value ? Category.footwear : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Y2K: null;
} | {
    minimal: null;
} | {
    streetwear: null;
} | {
    casual: null;
} | {
    party: null;
}): VibeTag {
    return "Y2K" in value ? VibeTag.Y2K : "minimal" in value ? VibeTag.minimal : "streetwear" in value ? VibeTag.streetwear : "casual" in value ? VibeTag.casual : "party" in value ? VibeTag.party : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shipped: null;
} | {
    delivered: null;
} | {
    processing: null;
}): OrderStatus {
    return "shipped" in value ? OrderStatus.shipped : "delivered" in value ? OrderStatus.delivered : "processing" in value ? OrderStatus.processing : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Deal>): Array<Deal> {
    return value.map((x)=>from_candid_Deal_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VibeTag>): Array<VibeTag> {
    return value.map((x)=>from_candid_VibeTag_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Category>): Array<Category> {
    return value.map((x)=>from_candid_Category_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Review>): Array<Review> {
    return value.map((x)=>from_candid_Review_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n37(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Deal_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Deal): _Deal {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_Product_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Product): _Product {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Review_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Review): _Review {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_StylePreferences_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StylePreferences): _StylePreferences {
    return to_candid_record_n49(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n47(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_VibeTag_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VibeTag): _VibeTag {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    description: string;
    isActive: boolean;
    discount: bigint;
    products: Array<Product>;
    isFlashSale: boolean;
}): {
    id: bigint;
    title: string;
    description: string;
    isActive: boolean;
    discount: bigint;
    products: Array<_Product>;
    isFlashSale: boolean;
} {
    return {
        id: value.id,
        title: value.title,
        description: value.description,
        isActive: value.isActive,
        discount: value.discount,
        products: to_candid_vec_n14(_uploadFile, _downloadFile, value.products),
        isFlashSale: value.isFlashSale
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    trendTags: Array<string>;
    name: string;
    videoPreview?: string;
    description: string;
    category: Category;
    price: bigint;
    vibeTags: Array<VibeTag>;
    images: Array<string>;
}): {
    id: bigint;
    trendTags: Array<string>;
    name: string;
    videoPreview: [] | [string];
    description: string;
    category: _Category;
    price: bigint;
    vibeTags: Array<_VibeTag>;
    images: Array<string>;
} {
    return {
        id: value.id,
        trendTags: value.trendTags,
        name: value.name,
        videoPreview: value.videoPreview ? candid_some(value.videoPreview) : candid_none(),
        description: value.description,
        category: to_candid_Category_n3(_uploadFile, _downloadFile, value.category),
        price: value.price,
        vibeTags: to_candid_vec_n5(_uploadFile, _downloadFile, value.vibeTags),
        images: value.images
    };
}
function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    shippingAddress: string;
    stylePreferences: StylePreferences;
}): {
    name: string;
    email: string;
    shippingAddress: string;
    stylePreferences: _StylePreferences;
} {
    return {
        name: value.name,
        email: value.email,
        shippingAddress: value.shippingAddress,
        stylePreferences: to_candid_StylePreferences_n48(_uploadFile, _downloadFile, value.stylePreferences)
    };
}
function to_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    preferredCategories: Array<Category>;
    excludedColors?: Array<string>;
    dislikedVibes: Array<VibeTag>;
    budgetRange: [bigint, bigint];
    preferredVibes: Array<VibeTag>;
}): {
    preferredCategories: Array<_Category>;
    excludedColors: [] | [Array<string>];
    dislikedVibes: Array<_VibeTag>;
    budgetRange: [bigint, bigint];
    preferredVibes: Array<_VibeTag>;
} {
    return {
        preferredCategories: to_candid_vec_n50(_uploadFile, _downloadFile, value.preferredCategories),
        excludedColors: value.excludedColors ? candid_some(value.excludedColors) : candid_none(),
        dislikedVibes: to_candid_vec_n5(_uploadFile, _downloadFile, value.dislikedVibes),
        budgetRange: value.budgetRange,
        preferredVibes: to_candid_vec_n5(_uploadFile, _downloadFile, value.preferredVibes)
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    text: string;
    user: Principal;
    productId: bigint;
    isInfluencerPick: boolean;
    rating: bigint;
    influencerQuote?: string;
}): {
    id: bigint;
    text: string;
    user: Principal;
    productId: bigint;
    isInfluencerPick: boolean;
    rating: bigint;
    influencerQuote: [] | [string];
} {
    return {
        id: value.id,
        text: value.text,
        user: value.user,
        productId: value.productId,
        isInfluencerPick: value.isInfluencerPick,
        rating: value.rating,
        influencerQuote: value.influencerQuote ? candid_some(value.influencerQuote) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    clothing: null;
} | {
    accessories: null;
} | {
    footwear: null;
} {
    return value == Category.clothing ? {
        clothing: null
    } : value == Category.accessories ? {
        accessories: null
    } : value == Category.footwear ? {
        footwear: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VibeTag): {
    Y2K: null;
} | {
    minimal: null;
} | {
    streetwear: null;
} | {
    casual: null;
} | {
    party: null;
} {
    return value == VibeTag.Y2K ? {
        Y2K: null
    } : value == VibeTag.minimal ? {
        minimal: null
    } : value == VibeTag.streetwear ? {
        streetwear: null
    } : value == VibeTag.casual ? {
        casual: null
    } : value == VibeTag.party ? {
        party: null
    } : value;
}
function to_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Product>): Array<_Product> {
    return value.map((x)=>to_candid_Product_n1(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<VibeTag>): Array<_VibeTag> {
    return value.map((x)=>to_candid_VibeTag_n6(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Category>): Array<_Category> {
    return value.map((x)=>to_candid_Category_n3(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
